



if dividend % divisor ==0;
print(f'""







      2
      quotient, remainder = divmod(23,5)

      print(quotient)
      print(remainder)

      is divisible =(remainder ==0)

      3
      number =30
      if number %3 == and number % 5==0;
      print("Divisible by 15")

      if number % 2== 0 or number % 7 ==0;
      print("Maeches criteria")


      4
      numbers = [12,15,22,44,55,60]
      divisor = 5

      divisible by five = [x for x in numbers if x % divisor ==0]
      print (divible by five)
